# Description: RTA-WRT Theme for LuCI
# Author: Design
# License: GPL-3.0

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Design Theme
LUCI_DEPENDS:=+curl +jsonfilter
PKG_VERSION:=2.0
PKG_RELEASE:=20012025

CONFIG_LUCI_CSSTIDY:=

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
