#!/bin/sh

NFT_DIR="/etc/nftables.d"
NFT_FILE="$NFT_DIR/ttl64.nft"
mkdir -p "$NFT_DIR"
rm -f "$NFT_DIR"/*


chmod +x /etc/init.d/nft-custom-ttl
/etc/init.d/nft-custom-ttl enable
/etc/init.d/nft-custom-ttl start

{
cat << 'EOF'
chain mangle_prerouting_ttl64 {
  type filter hook prerouting priority 300; policy accept;
  counter ip ttl set 64
}
chain mangle_postrouting_ttl64 {
  type filter hook postrouting priority 300; policy accept;
  counter ip ttl set 64
}
chain mangle_prerouting_hoplimit64 {
  type filter hook prerouting priority 300; policy accept;
  counter ip6 hoplimit set 64
EOF

for iface in $(ls /sys/class/net/ | grep '^wwan'); do
    echo "  iifname \"$iface\" ip6 hoplimit set 64"
done

echo "}"

cat << 'EOF'
chain mangle_postrouting_hoplimit64 {
  type filter hook postrouting priority 300; policy accept;
  counter ip6 hoplimit set 64
EOF

for iface in $(ls /sys/class/net/ | grep '^wwan'); do
    echo "  oifname \"$iface\" ip6 hoplimit set 64"
done

echo "}"
} > "$NFT_FILE"

/etc/init.d/firewall restart

[ -e /dev/ttyUSB3 ] && echo "AT+CFUN=1" > /dev/ttyUSB3

exit 0
