#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.design >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.design=/luci-static/design
		set luci.main.mediaurlbase=/luci-static/design
		commit luci
	EOF
fi

exit 0
